name: CI/C++

run-name: ${{github.actor}} run CI

env: 
    CC: clang
    CXX: clang++

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - run: sudo apt-get update
            - run: sudo apt-get install g++ clang make cmake libboost-all-dev
            - name: Install dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y libgtest-dev
                cd /usr/src/gtest
                sudo cmake .
                sudo make
                cd ..
                sudo cp -r gtest /usr/lib
            - run: mkdir -p build && cd build && cmake .. && make
            - run: cd ..
            - run: sh create_debpkg.sh
            - name: Tests
              run: sh test.sh
            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                name: app
                path: ./http-server-dcsa.deb
